### ISSUE TITLE
他コントローラー対応について

### ISSUE THREAD

**Issue by saha209** [kusaanko/BveDenshadeGoInterface#1]
サハ209と申します。
プログラム改造で他のゲームコントローラー対応ができそうなので改修案を提示いたします。

★サハ209が所持して使えそうなコントローラー
【PS用コントローラー】
・SCPH-10010 ソニー Dual Shock 2
・TCPP-20001 電車でGO!コントローラー ワンハンドルタイプ
・SLPH-00051 電車でGO!コントローラー ツーハンドルタイプ

・JCｰPS101USVコンバータ
・JCｰPS201USVコンバータ

【PC用コントローラー】
・DGOC-44U 電車でGO!コントローラー ツーハンドルタイプ
・電車でGO!旅情編コントローラー
・OHC-PC01A 三鶯重工 鉄道運転ｼｭﾐﾚ-ﾀ-⽤ ﾜﾝﾊﾝﾄﾞﾙｺﾝﾄﾛ-ﾗ- 

【任天堂switchコントローラー】
・Joy-ConL
・Joy-ConR
↑Bluetooth接続でゲームコントローラーとして認識してくれる。これいる？
(・瑞起製 電車でGO！！ はしろう山手線コントローラー)

※PS2用コントローラーはPCにUSB接続してもゲームコントローラーとして認識しない。

★改修案
【ConfigForm.cs】

![bve-1123](https://user-images.githubusercontent.com/73500651/116694457-489b7d80-a9fa-11eb-971d-2ab62c220565.JPG)

・コントローラー割当以下の設定項目を削除。代わりにコントローラーごとの設定をプリセットで選択する方式にする。
・コントローラーごとに使用できるボタンが違うので、使用コントローラーのクリックごとにボタン割当の項目が変化することが理想的。

【Settings.cs】
・使用コントローラーごとにボタンの設定保存が変わるので改修が必要
・ある程度はボタン設定を重ねられそう
・重ねたら他のコントローラを使って設定変えて戻ったときに設定変わっちゃうかもしれないからやっぱりコントローラごとに設定を分けるべき？

【DenshadeGoInterface.cs】
・コントローラーごとにプログラムを書いて、使用コントローラーの設定から呼び出す方式が良さそう
・void Tick()はBVEのフレーム依存なので非同期処理にした方が軽くなる(って教わった)

プログラミング初心者で口下手なのですが、思いついたことを書き残しておきます。
後程当方でちょっと弄ってプルリク投げる予定です。

**Comment by kusaanko** [comment]
主に電車でGO!コントローラーですが様々なコントローラーに対応しようというアイディアですね。改修大変そうですがやってみようと思います。

**Comment by kusaanko** [comment]
この機能はBveNumerousControllerInterfaceにて実装することになりました。
